title = "sangbom.ha"
languageCode = "en"
defaultContentLanguage = "en"
enableRobotsTXT = true

# 서브모듈 방식이므로 theme만 지정
theme = "hugo-book"

[params]
  BookTheme = "light"
  BookSection = "docs"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
  [markup.highlight]
    style = "base16-snazzy"
